#!/bin/bash
# Memory Protocol enforcement hook for Claude Code.
#
# Tracks tool call activity and enforces search/store discipline:
#   - PostToolUse (all):    Increment counter, detect search/write tools, mid-session nudge
#   - PreToolUse (Skill):   Inject phase-specific search + store reminders
#   - PreToolUse (Edit/Write): Block file modifications until memory is searched (guard)
#   - SessionStart:         Fetch project context from Graphiti, reset counters
#   - Stop:                 Warn if too many calls without search or store
#
# State is stored in simple counter files under /tmp/.wmp-*
# Resets automatically on new session (via session_id tracking).
#
# Uses node for JSON parsing (python3 unavailable under asdf in hook context).
# Generated by Vanguard — do not edit manually.

EVENT="${1:-}"
INPUT=$(cat)

# ── Prerequisite: node must be available for JSON parsing ──
if ! command -v node &>/dev/null; then
  echo "WARNING: memory-protocol.sh requires node but it's not in PATH. Memory enforcement disabled." >&2
  exit 0
fi

# State file paths
STATE_DIR="/tmp"
FILE_SESSION="$STATE_DIR/.wmp-session"
FILE_TOTAL="$STATE_DIR/.wmp-total"
FILE_LAST_SEARCH="$STATE_DIR/.wmp-last-search"
FILE_LAST_WRITE="$STATE_DIR/.wmp-last-write"
FILE_LAST_BLOCKED="$STATE_DIR/.wmp-last-blocked"
FILE_CURRENT_PHASE="$STATE_DIR/.wmp-current-phase"

# Parse a JSON field from $INPUT using node
json_get() {
  echo "$INPUT" | node -e "
    let d='';
    process.stdin.on('data',c=>d+=c);
    process.stdin.on('end',()=>{
      try {
        const path='$1'.split('.');
        let v=JSON.parse(d);
        for(const k of path) v=v?.[k];
        console.log(v||'');
      } catch(e) { console.log(''); }
    });
  " 2>/dev/null || echo ""
}

# Read a counter file, default to 0
read_counter() {
  cat "$1" 2>/dev/null || echo "0"
}

# Reset counters for a new session
reset_if_new_session() {
  local session_id
  session_id=$(json_get "session_id")
  local stored_session
  stored_session=$(cat "$FILE_SESSION" 2>/dev/null || echo "")

  if [ -n "$session_id" ] && [ "$session_id" != "$stored_session" ]; then
    echo "$session_id" > "$FILE_SESSION"
    echo "0" > "$FILE_TOTAL"
    echo "0" > "$FILE_LAST_SEARCH"
    echo "0" > "$FILE_LAST_WRITE"
    echo "0" > "$FILE_LAST_BLOCKED"
    echo "" > "$FILE_CURRENT_PHASE"
  fi
}

case "$EVENT" in

  # ── PostToolUse: track all tool calls, detect search/write ──
  track)
    reset_if_new_session

    tool_name=$(json_get "tool_name")
    total=$(read_counter "$FILE_TOTAL")
    total=$((total + 1))
    echo "$total" > "$FILE_TOTAL"

    case "$tool_name" in
      mcp__vanguard__search_hybrid|mcp__vanguard__search_memory_facts|mcp__vanguard__search_nodes|mcp__vanguard__search_communities)
        echo "$total" > "$FILE_LAST_SEARCH"
        ;;
      mcp__vanguard__add_memory|mcp__vanguard__ingest_text)
        echo "$total" > "$FILE_LAST_WRITE"
        ;;
    esac

    # Mid-session nudge: remind to search if too many calls without checking memory
    MID_THRESHOLD=${VANGUARD_MEMORY_MID_THRESHOLD:-10}
    last_search=$(read_counter "$FILE_LAST_SEARCH")
    since_search=$((total - last_search))

    if [ "$since_search" -eq "$MID_THRESHOLD" ]; then
      echo "MEMORY PROTOCOL: $since_search tool calls without searching knowledge graph. Consider running search_hybrid to check for relevant decisions." >&2
    fi
    ;;

  # ── PreToolUse on Skill: phase-specific memory instructions ──
  phase)
    reset_if_new_session

    skill=$(json_get "tool_input.skill")

    # Build phase-specific context injection
    case "$skill" in
      vanguard.architect)
        CTX="MEMORY PROTOCOL — Phase start: /architect
1. SEARCH first: search_hybrid(query=\"decisions requirements architecture for [spec topic]\", group_id=\"...\") before starting
2. STORE when done: Decision (choices + rationale), Requirement (NFRs)"
        ;;
      vanguard.discover)
        CTX="MEMORY PROTOCOL — Phase start: /discover
1. SEARCH first: search_hybrid(query=\"context about [discovery topic]\", group_id=\"...\") before starting
2. STORE when done: Context (discoveries, risks, unknowns)"
        ;;
      vanguard.implement)
        CTX="MEMORY PROTOCOL — Phase start: /implement
1. SEARCH first: search_hybrid(query=\"patterns conventions solutions for [task topic]\", group_id=\"...\") before starting
2. STORE when done: Pattern (reusable patterns), Solution (non-obvious fixes)"
        ;;
      vanguard.plan)
        CTX="MEMORY PROTOCOL — Phase start: /plan
1. SEARCH first: search_hybrid(query=\"context decisions for [plan topic]\", group_id=\"...\") before starting
2. STORE when done: Context (task breakdown + sequencing rationale)"
        ;;
      vanguard.review)
        CTX="MEMORY PROTOCOL — Phase start: /review
1. SEARCH first: search_hybrid(query=\"patterns quality checks for [review topic]\", group_id=\"...\") before starting
2. STORE when done: Pattern (quality checks), Solution (defect patterns)"
        ;;
      vanguard.specify)
        CTX="MEMORY PROTOCOL — Phase start: /specify
1. SEARCH first: search_hybrid(query=\"requirements decisions for [spec topic]\", group_id=\"...\") before starting
2. STORE when done: Requirement (MUST-HAVEs), Decision (scope choices)"
        ;;
      *)
        # Not a memory-active phase — no injection
        exit 0
        ;;
    esac

    # Phase-awareness: reset search counter when entering a new phase
    # so the agent must search again for this phase's specific concerns
    total=$(read_counter "$FILE_TOTAL")
    previous_phase=$(cat "$FILE_CURRENT_PHASE" 2>/dev/null || echo "")

    if [ "$skill" != "$previous_phase" ]; then
      echo "$skill" > "$FILE_CURRENT_PHASE"
      # Only reset if not already in a forced-search state (negative sentinel)
      # Negative values mean session-init failed — don't overwrite with 0
      current_last_search=$(read_counter "$FILE_LAST_SEARCH")
      if [ "$current_last_search" -ge 0 ] 2>/dev/null; then
        echo "0" > "$FILE_LAST_SEARCH"
      fi
    fi

    # Also remind about previous phase's knowledge
    last_write=$(read_counter "$FILE_LAST_WRITE")
    since_write=$((total - last_write))

    if [ "$since_write" -gt 5 ]; then
      CTX="$CTX
NOTE: $since_write tool calls since last knowledge store. Did the previous phase produce decisions, patterns, or solutions worth storing?"
    fi

    # Output JSON for PreToolUse — allow the skill, inject context
    node -e "
      let d='';
      process.stdin.on('data',c=>d+=c);
      process.stdin.on('end',()=>{
        console.log(JSON.stringify({
          hookSpecificOutput: {
            hookEventName: 'PreToolUse',
            permissionDecision: 'allow',
            additionalContext: d.trim()
          }
        }));
      });
    " <<< "$CTX"
    ;;

  # ── PreToolUse on Edit/Write: block modifications until memory is searched ──
  guard)
    # Fail-open: if state files are missing (container restart, tmpfs cleared),
    # allow the operation rather than incorrectly blocking
    if [ ! -f "$FILE_TOTAL" ] || [ ! -f "$FILE_LAST_SEARCH" ]; then
      exit 0
    fi

    total=$(read_counter "$FILE_TOTAL")
    last_search=$(read_counter "$FILE_LAST_SEARCH")
    since_search=$((total - last_search))

    GUARD_THRESHOLD=${VANGUARD_MEMORY_MID_THRESHOLD:-10}

    if [ "$since_search" -gt "$GUARD_THRESHOLD" ]; then
      # Deny the edit/write — agent must search memory first
      node -e "
        console.log(JSON.stringify({
          hookSpecificOutput: {
            hookEventName: 'PreToolUse',
            permissionDecision: 'deny',
            reason: 'MEMORY PROTOCOL: $since_search tool calls without searching knowledge graph. You MUST run search_hybrid(query=\"relevant topic\", group_id=\"vanguard--vanguard-cli\") before modifying any files. This ensures stored decisions and patterns are respected.'
          }
        }));
      "
    fi
    ;;

  # ── SessionStart: fetch project context from Graphiti ──
  session-init)
    reset_if_new_session

    # Reset all counters for fresh session
    echo "0" > "$FILE_TOTAL"
    echo "0" > "$FILE_LAST_WRITE"
    echo "0" > "$FILE_LAST_BLOCKED"
    echo "" > "$FILE_CURRENT_PHASE"

    # Check prerequisites before fetching
    if [ -z "$VANGUARD_TOKEN" ]; then
      echo "WARNING: VANGUARD_TOKEN not set. Memory protocol disabled for this session." >&2
      # Disable guard by setting last_search high — no enforcement without auth
      echo "999999" > "$FILE_LAST_SEARCH"
      exit 0
    fi

    if ! command -v vanguard &>/dev/null; then
      echo "WARNING: vanguard CLI not in PATH. Memory context will not be loaded." >&2
      # Force guard to fire immediately — agent must search via MCP tools instead
      # Sentinel -11 ensures since_search = 0 - (-11) = 11 > 10 at total=0
      echo "-11" > "$FILE_LAST_SEARCH"
      exit 0
    fi

    # Fetch project context from Graphiti knowledge graph
    CONTEXT=$(vanguard memory hook session-start 2>/dev/null || echo "")

    if [ -n "$CONTEXT" ]; then
      # Success: context was fetched — grant grace period by marking as "searched"
      echo "0" > "$FILE_LAST_SEARCH"
      echo "$CONTEXT"
    else
      # Failure: API down or empty response — force guard to fire immediately
      # Sentinel -11 ensures since_search = 0 - (-11) = 11 > 10 at total=0
      echo "-11" > "$FILE_LAST_SEARCH"
    fi
    ;;

  # ── Stop: check counters, block if thresholds exceeded ──
  check)
    total=$(read_counter "$FILE_TOTAL")
    last_search=$(read_counter "$FILE_LAST_SEARCH")
    last_write=$(read_counter "$FILE_LAST_WRITE")
    last_blocked=$(read_counter "$FILE_LAST_BLOCKED")

    since_search=$((total - last_search))
    since_write=$((total - last_write))
    since_blocked=$((total - last_blocked))

    # Don't re-block within 5 tool calls of last block (prevent loops)
    if [ "$since_blocked" -lt 5 ] && [ "$last_blocked" -gt 0 ]; then
      exit 0
    fi

    THRESHOLD=${VANGUARD_MEMORY_THRESHOLD:-10}
    messages=""

    if [ "$since_search" -gt "$THRESHOLD" ]; then
      messages="MEMORY PROTOCOL: $since_search tool calls without searching knowledge graph. Run search_hybrid before continuing."
    fi

    if [ "$since_write" -gt "$THRESHOLD" ]; then
      if [ -n "$messages" ]; then
        messages="$messages "
      fi
      messages="${messages}MEMORY PROTOCOL: $since_write tool calls without storing knowledge. Check triggers: Decision? Pattern? Solution? Requirement? Context at risk?"
    fi

    if [ -n "$messages" ]; then
      # Record that we reminded
      echo "$total" > "$FILE_LAST_BLOCKED"
      # Output as Stop hook feedback (non-blocking) — shown to Claude as context
      echo "$messages" >&2
      exit 0
    fi
    ;;

  *)
    echo "Usage: memory-protocol.sh {track|phase|guard|session-init|check}" >&2
    exit 1
    ;;
esac
