/**
 * Tutorial command — Initialize and manage Vanguard guided tutorials.
 *
 * Sets up a repository in tutorial mode with automatic phase inspection hooks.
 * The tutorial walks developers through all 6 Vanguard phases using the
 * Ember & Oak Coffee Roasters wholesale platform as a guided exercise.
 *
 * Usage:
 *   vanguard tutorial init [repo-path]   — Set up tutorial mode in a repo
 *   vanguard tutorial status              — Check tutorial mode status
 *   vanguard tutorial stop                — Disable tutorial mode
 */

import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import * as p from '@clack/prompts'
import { Command } from 'commander'
import pc from 'picocolors'

// ─── Tutorial hook templates ────────────────────────────────────────────────
// These are embedded directly so they can be written to any target repo
// without needing to ship separate template files.

const TUTORIAL_HOOK_SH = `#!/bin/bash
# Tutorial inspection hook for Claude Code.
#
# Fires after Vanguard phase commands complete (PostToolUse on Skill).
# Detects which phase just finished and injects an instruction for Claude
# to run /vanguard:tutorial.inspect <phase> for automatic artifact feedback.
#
# Tutorial mode is tracked via a state file set by /vanguard:tutorial.start.
# When tutorial mode is inactive, the hook exits silently (zero overhead).
#
# Generated by Vanguard — do not edit manually.

INPUT=$(cat)

# State file paths
STATE_DIR="/tmp"
FILE_TUTORIAL_ACTIVE="$STATE_DIR/.wpt-tutorial-active"
FILE_TUTORIAL_SESSION="$STATE_DIR/.wpt-tutorial-session"

# Parse a JSON field from $INPUT using node
json_get() {
  echo "$INPUT" | node -e "
    let d='';
    process.stdin.on('data',c=>d+=c);
    process.stdin.on('end',()=>{
      try {
        const path='$1'.split('.');
        let v=JSON.parse(d);
        for(const k of path) v=v?.[k];
        console.log(v||'');
      } catch(e) { console.log(''); }
    });
  " 2>/dev/null || echo ""
}

# Check if tutorial mode is active
is_tutorial_active() {
  [ -f "$FILE_TUTORIAL_ACTIVE" ] && [ "$(cat "$FILE_TUTORIAL_ACTIVE" 2>/dev/null)" = "true" ]
}

# Reset state for new sessions
reset_if_new_session() {
  local session_id
  session_id=$(json_get "session_id")
  local stored_session
  stored_session=$(cat "$FILE_TUTORIAL_SESSION" 2>/dev/null || echo "")

  if [ -n "$session_id" ] && [ "$session_id" != "$stored_session" ]; then
    echo "$session_id" > "$FILE_TUTORIAL_SESSION"
  fi
}

reset_if_new_session

# Exit silently if tutorial mode is not active
if ! is_tutorial_active; then
  exit 0
fi

# Get the skill that just completed
skill=$(json_get "tool_input.skill")

# Map skill to tutorial phase
case "$skill" in
  vanguard.discover)
    PHASE="discover"
    PHASE_NAME="Discovery"
    ARTIFACT=".vanguard/specs/discovery.md"
    NEXT_PHASE="Specification"
    NEXT_CMD="/vanguard.specify"
    ;;
  vanguard.specify)
    PHASE="specify"
    PHASE_NAME="Specification"
    ARTIFACT=".vanguard/specs/*.md (latest spec)"
    NEXT_PHASE="Architecture"
    NEXT_CMD="/vanguard.architect"
    ;;
  vanguard.architect)
    PHASE="architect"
    PHASE_NAME="Architecture"
    ARTIFACT=".vanguard/plans/*.md (latest plan)"
    NEXT_PHASE="Planning"
    NEXT_CMD="/vanguard.plan"
    ;;
  vanguard.plan)
    PHASE="plan"
    PHASE_NAME="Planning"
    ARTIFACT=".vanguard/tasks/**/task-*.md"
    NEXT_PHASE="Implementation"
    NEXT_CMD="/vanguard.implement"
    ;;
  vanguard.implement)
    PHASE="implement"
    PHASE_NAME="Implementation"
    ARTIFACT="src/ (implementation code)"
    NEXT_PHASE="Review"
    NEXT_CMD="/vanguard.review"
    ;;
  vanguard.review)
    PHASE="review"
    PHASE_NAME="Review"
    ARTIFACT="Test results and acceptance criteria"
    NEXT_PHASE="Complete"
    NEXT_CMD=""
    ;;
  *)
    exit 0
    ;;
esac

# Build the inspection instruction
CTX="TUTORIAL MODE — \${PHASE_NAME} phase complete.

You MUST now run /vanguard:tutorial.inspect \${PHASE} to inspect the learner's artifact and provide structured feedback.

The artifact to inspect: \${ARTIFACT}
Next phase after inspection: \${NEXT_PHASE}"

if [ -n "$NEXT_CMD" ]; then
  CTX="\${CTX}
Next command: \${NEXT_CMD}"
fi

# Output JSON for PostToolUse
node -e "
  let d='';
  process.stdin.on('data',c=>d+=c);
  process.stdin.on('end',()=>{
    console.log(JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PostToolUse',
        additionalContext: d.trim()
      }
    }));
  });
" <<< "$CTX"
`

const TUTORIAL_ACTIVATE_SH = `#!/bin/bash
# Tutorial mode activation/deactivation helper.
#
# Usage:
#   tutorial-activate.sh on    — Enable tutorial hooks
#   tutorial-activate.sh off   — Disable tutorial hooks
#   tutorial-activate.sh status — Check if tutorial mode is active
#
# Generated by Vanguard — do not edit manually.

STATE_DIR="/tmp"
FILE_TUTORIAL_ACTIVE="$STATE_DIR/.wpt-tutorial-active"

case "\${1:-status}" in
  on)
    echo "true" > "$FILE_TUTORIAL_ACTIVE"
    echo "Tutorial mode activated. Phase hooks will trigger automatic inspection."
    ;;
  off)
    rm -f "$FILE_TUTORIAL_ACTIVE"
    echo "Tutorial mode deactivated. Phase hooks disabled."
    ;;
  status)
    if [ -f "$FILE_TUTORIAL_ACTIVE" ] && [ "$(cat "$FILE_TUTORIAL_ACTIVE" 2>/dev/null)" = "true" ]; then
      echo "active"
    else
      echo "inactive"
    fi
    ;;
  *)
    echo "Usage: tutorial-activate.sh {on|off|status}" >&2
    exit 1
    ;;
esac
`

// ─── Helper: merge tutorial hook into settings.json ─────────────────────────

interface HookEntry {
	type: string
	command: string
	timeout: number
}

interface HookGroup {
	matcher?: string
	hooks: HookEntry[]
}

interface SettingsJson {
	hooks?: Record<string, HookGroup[]>
	[key: string]: unknown
}

async function mergeHookConfig(projectRoot: string): Promise<boolean> {
	const settingsPath = join(projectRoot, '.claude', 'settings.json')

	let settings: SettingsJson = {}
	try {
		const raw = await readFile(settingsPath, 'utf-8')
		settings = JSON.parse(raw) as SettingsJson
	} catch {
		// No existing settings — start fresh
	}

	if (!settings.hooks) {
		settings.hooks = {}
	}

	if (!settings.hooks.PostToolUse) {
		settings.hooks.PostToolUse = []
	}

	// Check if tutorial hook already registered
	const tutorialHookCmd = '"$CLAUDE_PROJECT_DIR"/.claude/hooks/tutorial-hook.sh'
	const alreadyWired = settings.hooks.PostToolUse.some((group) =>
		group.hooks?.some((h) => h.command === tutorialHookCmd),
	)

	if (alreadyWired) {
		return false // Already configured
	}

	// Add tutorial hook entry
	settings.hooks.PostToolUse.push({
		matcher: 'Skill',
		hooks: [
			{
				type: 'command',
				command: tutorialHookCmd,
				timeout: 3,
			},
		],
	})

	await mkdir(dirname(settingsPath), { recursive: true })
	await writeFile(settingsPath, `${JSON.stringify(settings, null, 2)}\n`, 'utf-8')
	return true
}

// ─── Helper: update manifest with tutorial section ──────────────────────────

async function updateManifest(projectRoot: string): Promise<void> {
	const manifestPath = join(projectRoot, 'vanguard.manifest.yaml')

	let content: string
	try {
		content = await readFile(manifestPath, 'utf-8')
	} catch {
		p.log.warn('No vanguard.manifest.yaml found. Run `vanguard init` first.')
		return
	}

	// Check if tutorial section already exists
	if (content.includes('tutorial:')) {
		return // Already has tutorial config
	}

	// Append tutorial section before documents section (or at end)
	const tutorialYaml = `tutorial:
  enabled: true
  repository: vanguard-demo
  feature: ember-oak-wholesale
  academyModuleId: gcm46s2jqb0ss98ld0u6fxdn
  commands:
    start: /vanguard:tutorial.start
    inspect: /vanguard:tutorial.inspect
  hooks:
    hook: .claude/hooks/tutorial-hook.sh
    activate: .claude/hooks/tutorial-activate.sh
`

	if (content.includes('documents:')) {
		content = content.replace('documents:', `${tutorialYaml}documents:`)
	} else {
		content += `\n${tutorialYaml}`
	}

	await writeFile(manifestPath, content, 'utf-8')
}

// ─── Subcommand: tutorial init ──────────────────────────────────────────────

const initTutorialCommand = new Command('init')
	.description('Set up tutorial mode in the current repository')
	.argument('[path]', 'Project path', '.')
	.action(async (targetPath: string) => {
		const projectRoot = resolve(targetPath)

		console.log()
		p.intro(pc.bgCyan(pc.black(' vanguard tutorial init ')))

		// Step 1: Write hook files
		const hookSpinner = p.spinner()
		hookSpinner.start('Installing tutorial hooks')

		try {
			const hooksDir = join(projectRoot, '.claude', 'hooks')
			await mkdir(hooksDir, { recursive: true })

			const hookPath = join(hooksDir, 'tutorial-hook.sh')
			const activatePath = join(hooksDir, 'tutorial-activate.sh')

			await writeFile(hookPath, TUTORIAL_HOOK_SH, 'utf-8')
			await writeFile(activatePath, TUTORIAL_ACTIVATE_SH, 'utf-8')
			await chmod(hookPath, 0o755)
			await chmod(activatePath, 0o755)

			hookSpinner.stop('Tutorial hooks installed')
		} catch (error) {
			hookSpinner.stop('Failed to install hooks')
			p.log.error(error instanceof Error ? error.message : String(error))
			process.exit(1)
		}

		// Step 2: Wire hooks into settings.json
		const wireSpinner = p.spinner()
		wireSpinner.start('Configuring Claude Code hooks')

		try {
			const wired = await mergeHookConfig(projectRoot)
			if (wired) {
				wireSpinner.stop('Tutorial hook registered in settings.json')
			} else {
				wireSpinner.stop('Tutorial hook already registered')
			}
		} catch (error) {
			wireSpinner.stop('Hook wiring failed')
			p.log.warn(error instanceof Error ? error.message : String(error))
		}

		// Step 3: Update manifest
		const manifestSpinner = p.spinner()
		manifestSpinner.start('Updating manifest')

		try {
			await updateManifest(projectRoot)
			manifestSpinner.stop('Manifest updated with tutorial config')
		} catch (error) {
			manifestSpinner.stop('Manifest update failed')
			p.log.warn(error instanceof Error ? error.message : String(error))
		}

		// Step 4: Summary
		console.log()
		p.log.success(pc.bold('Tutorial mode ready!'))
		console.log()
		p.log.info(
			pc.dim('Project: ') +
				pc.cyan('Ember & Oak Coffee Roasters') +
				pc.dim(' — Wholesale Order Platform'),
		)
		p.log.info(
			pc.dim('Starting materials: ') +
				pc.cyan('docs/client-transcript.md') +
				pc.dim(', ') +
				pc.cyan('docs/product-catalog.csv'),
		)
		console.log()
		p.log.step(
			`Run ${pc.cyan('/vanguard:tutorial.start')} in Claude Code to begin the guided walkthrough.`,
		)
		p.log.step('The tutorial walks you through all 6 Vanguard phases:')
		p.log.info(
			pc.dim(
				'  1. Discovery → 2. Specification → 3. Architecture → 4. Planning → 5. Implementation → 6. Review',
			),
		)
		p.log.step(
			'After each phase, a hook automatically inspects your work and provides expert feedback.',
		)

		p.outro(pc.green('Happy building!'))
	})

// ─── Subcommand: tutorial status ────────────────────────────────────────────

const statusTutorialCommand = new Command('status')
	.description('Check tutorial mode status')
	.action(async () => {
		console.log()
		p.intro(pc.bgCyan(pc.black(' vanguard tutorial status ')))

		const cwd = process.cwd()

		// Check hook files exist
		const hookPath = join(cwd, '.claude', 'hooks', 'tutorial-hook.sh')
		const activatePath = join(cwd, '.claude', 'hooks', 'tutorial-activate.sh')

		let hookInstalled = false
		let activateInstalled = false
		try {
			await readFile(hookPath)
			hookInstalled = true
		} catch {
			/* not found */
		}
		try {
			await readFile(activatePath)
			activateInstalled = true
		} catch {
			/* not found */
		}

		if (hookInstalled && activateInstalled) {
			p.log.success(`Tutorial hooks: ${pc.green('installed')}`)
		} else {
			p.log.warn(`Tutorial hooks: ${pc.yellow('not installed')}`)
			p.log.info(`Run ${pc.cyan('vanguard tutorial init')} to set up tutorial mode.`)
		}

		// Check runtime state
		const stateFile = '/tmp/.wpt-tutorial-active'
		let runtimeActive = false
		try {
			const state = await readFile(stateFile, 'utf-8')
			runtimeActive = state.trim() === 'true'
		} catch {
			/* not found */
		}

		if (runtimeActive) {
			p.log.success(`Tutorial mode: ${pc.green('active')}`)
		} else {
			p.log.info(`Tutorial mode: ${pc.dim('inactive')}`)
			if (hookInstalled) {
				p.log.info(`Run ${pc.cyan('/vanguard:tutorial.start')} in Claude Code to activate.`)
			}
		}

		p.outro('')
	})

// ─── Subcommand: tutorial stop ──────────────────────────────────────────────

const stopTutorialCommand = new Command('stop')
	.description('Disable tutorial mode')
	.action(async () => {
		console.log()
		p.intro(pc.bgCyan(pc.black(' vanguard tutorial stop ')))

		// Deactivate runtime state
		try {
			await writeFile('/tmp/.wpt-tutorial-active', 'false', 'utf-8')
			p.log.success('Tutorial mode deactivated')
		} catch {
			p.log.info('Tutorial mode was already inactive')
		}

		p.log.info(
			pc.dim('Hooks remain installed. Run ') +
				pc.cyan('/vanguard:tutorial.start') +
				pc.dim(' to reactivate.'),
		)

		p.outro(pc.green('Tutorial stopped.'))
	})

// ─── Export command group ───────────────────────────────────────────────────

export const tutorialCommand = new Command('tutorial')
	.description('Manage the Vanguard guided tutorial')
	.addCommand(initTutorialCommand)
	.addCommand(statusTutorialCommand)
	.addCommand(stopTutorialCommand)
