#!/bin/bash
# Memory Protocol enforcement hook for Claude Code.
#
# Tracks tool call activity and enforces search/store discipline:
#   - PostToolUse (all):    Increment counter, detect search/write tools
#   - PreToolUse (Skill):   Inject phase-specific search + store reminders
#   - Stop:                 Block if too many calls without search or store
#
# State is stored in simple counter files under /tmp/.wmp-*
# Resets automatically on new session (via session_id tracking).
#
# Uses node for JSON parsing (python3 unavailable under asdf in hook context).
# Generated by WayPoint — do not edit manually.

EVENT="${1:-}"
INPUT=$(cat)

# State file paths
STATE_DIR="/tmp"
FILE_SESSION="$STATE_DIR/.wmp-session"
FILE_TOTAL="$STATE_DIR/.wmp-total"
FILE_LAST_SEARCH="$STATE_DIR/.wmp-last-search"
FILE_LAST_WRITE="$STATE_DIR/.wmp-last-write"
FILE_LAST_BLOCKED="$STATE_DIR/.wmp-last-blocked"

# Parse a JSON field from $INPUT using node
json_get() {
  echo "$INPUT" | node -e "
    let d='';
    process.stdin.on('data',c=>d+=c);
    process.stdin.on('end',()=>{
      try {
        const path='$1'.split('.');
        let v=JSON.parse(d);
        for(const k of path) v=v?.[k];
        console.log(v||'');
      } catch(e) { console.log(''); }
    });
  " 2>/dev/null || echo ""
}

# Read a counter file, default to 0
read_counter() {
  cat "$1" 2>/dev/null || echo "0"
}

# Reset counters for a new session
reset_if_new_session() {
  local session_id
  session_id=$(json_get "session_id")
  local stored_session
  stored_session=$(cat "$FILE_SESSION" 2>/dev/null || echo "")

  if [ -n "$session_id" ] && [ "$session_id" != "$stored_session" ]; then
    echo "$session_id" > "$FILE_SESSION"
    echo "0" > "$FILE_TOTAL"
    echo "0" > "$FILE_LAST_SEARCH"
    echo "0" > "$FILE_LAST_WRITE"
    echo "0" > "$FILE_LAST_BLOCKED"
  fi
}

case "$EVENT" in

  # ── PostToolUse: track all tool calls, detect search/write ──
  track)
    reset_if_new_session

    tool_name=$(json_get "tool_name")
    total=$(read_counter "$FILE_TOTAL")
    total=$((total + 1))
    echo "$total" > "$FILE_TOTAL"

    case "$tool_name" in
      mcp__waypoint__search_hybrid|mcp__waypoint__search_memory_facts|mcp__waypoint__search_nodes|mcp__waypoint__search_communities)
        echo "$total" > "$FILE_LAST_SEARCH"
        ;;
      mcp__waypoint__add_memory|mcp__waypoint__ingest_text)
        echo "$total" > "$FILE_LAST_WRITE"
        ;;
    esac
    ;;

  # ── PreToolUse on Skill: phase-specific memory instructions ──
  phase)
    reset_if_new_session

    skill=$(json_get "tool_input.skill")

    # Build phase-specific context injection
    case "$skill" in
      waypoint.architect)
        CTX="MEMORY PROTOCOL — Action start: /architect
1. SEARCH first: search_hybrid(query=\"decisions requirements architecture for [spec topic]\", group_id=\"...\") before starting
2. STORE when done: Decision (choices + rationale), Requirement (NFRs)"
        ;;
      waypoint.discover)
        CTX="MEMORY PROTOCOL — Action start: /discover
1. SEARCH first: search_hybrid(query=\"context about [discovery topic]\", group_id=\"...\") before starting
2. STORE when done: Context (discoveries, risks, unknowns)"
        ;;
      waypoint.implement)
        CTX="MEMORY PROTOCOL — Action start: /implement
1. SEARCH first: search_hybrid(query=\"patterns conventions solutions for [task topic]\", group_id=\"...\") before starting
2. STORE when done: Pattern (reusable patterns), Solution (non-obvious fixes)"
        ;;
      waypoint.plan)
        CTX="MEMORY PROTOCOL — Action start: /plan
1. SEARCH first: search_hybrid(query=\"context decisions for [plan topic]\", group_id=\"...\") before starting
2. STORE when done: Context (task breakdown + sequencing rationale)"
        ;;
      waypoint.review)
        CTX="MEMORY PROTOCOL — Action start: /review
1. SEARCH first: search_hybrid(query=\"patterns quality checks for [review topic]\", group_id=\"...\") before starting
2. STORE when done: Pattern (quality checks), Solution (defect patterns)"
        ;;
      waypoint.specify)
        CTX="MEMORY PROTOCOL — Action start: /specify
1. SEARCH first: search_hybrid(query=\"requirements decisions for [spec topic]\", group_id=\"...\") before starting
2. STORE when done: Requirement (MUST-HAVEs), Decision (scope choices)"
        ;;
      *)
        # Not a memory-active action — no injection
        exit 0
        ;;
    esac

    # Also remind about previous action's knowledge
    total=$(read_counter "$FILE_TOTAL")
    last_write=$(read_counter "$FILE_LAST_WRITE")
    since_write=$((total - last_write))

    if [ "$since_write" -gt 5 ]; then
      CTX="$CTX
NOTE: $since_write tool calls since last knowledge store. Did the previous action produce decisions, patterns, or solutions worth storing?"
    fi

    # Output JSON for PreToolUse — allow the skill, inject context
    node -e "
      let d='';
      process.stdin.on('data',c=>d+=c);
      process.stdin.on('end',()=>{
        console.log(JSON.stringify({
          hookSpecificOutput: {
            hookEventName: 'PreToolUse',
            permissionDecision: 'allow',
            additionalContext: d.trim()
          }
        }));
      });
    " <<< "$CTX"
    ;;

  # ── Stop: check counters, block if thresholds exceeded ──
  check)
    total=$(read_counter "$FILE_TOTAL")
    last_search=$(read_counter "$FILE_LAST_SEARCH")
    last_write=$(read_counter "$FILE_LAST_WRITE")
    last_blocked=$(read_counter "$FILE_LAST_BLOCKED")

    since_search=$((total - last_search))
    since_write=$((total - last_write))
    since_blocked=$((total - last_blocked))

    # Don't re-block within 5 tool calls of last block (prevent loops)
    if [ "$since_blocked" -lt 5 ] && [ "$last_blocked" -gt 0 ]; then
      exit 0
    fi

    THRESHOLD=${WAYPOINT_MEMORY_THRESHOLD:-20}
    messages=""

    if [ "$since_search" -gt "$THRESHOLD" ]; then
      messages="MEMORY PROTOCOL: $since_search tool calls without searching knowledge graph. Run search_hybrid before continuing."
    fi

    if [ "$since_write" -gt "$THRESHOLD" ]; then
      if [ -n "$messages" ]; then
        messages="$messages "
      fi
      messages="${messages}MEMORY PROTOCOL: $since_write tool calls without storing knowledge. Check triggers: Decision? Pattern? Solution? Requirement? Context at risk?"
    fi

    if [ -n "$messages" ]; then
      # Record that we reminded
      echo "$total" > "$FILE_LAST_BLOCKED"
      # Output as Stop hook feedback (non-blocking) — shown to Claude as context
      echo "$messages" >&2
      exit 0
    fi
    ;;

  *)
    echo "Usage: memory-protocol.sh {track|phase|check}" >&2
    exit 1
    ;;
esac
